### ISSUE TITLE
'Attempt to decode JSON with unexpected mimetype: '

### ISSUE THREAD

**Issue by thijsdejong** [iMicknl/python-tahoma-api#35]
I'm currently unable to open my covers using Home Assistant. I did not restart yet since I thought the errors might be useful to handle in the future.
```
0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://tahomalink.com/enduser-mobile-web/enduserAPI/exec/apply')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/cover.py", line 199, in async_open_cover
    await self.async_execute_command(
  File "/config/custom_components/tahoma/tahoma_device.py", line 155, in async_execute_command
    await self.coordinator.client.execute_command(
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 157, in execute_command
    return await self.execute_commands(device_url, [command], label)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 170, in execute_commands
    response = await self.__post("exec/apply", payload)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 196, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 209, in check_response
    result = await response.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://tahomalink.com/enduser-mobile-web/enduserAPI/exec/apply')
Failed to call service cover/open_cover. 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://tahomalink.com/enduser-mobile-web/enduserAPI/exec/apply')
```

It looks like this started happening after getting the following error:
```
Logger: custom_components.tahoma
Source: helpers/update_coordinator.py:165
Integration: Somfy TaHoma (documentation, issues)
First occurred: 7:07:09 AM (1 occurrences)
Last logged: 7:07:09 AM

Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: Cannot connect to host tahomalink.com:443 ssl:default [Connect call failed ('178.32.15.131', 443)]
```

Hope this helps :) Problem was solved immediately after restart. So it seems to me it lost connection but never tried to reconnect?

**Comment by tetienne** [comment]
I met this error randomly too. During several days it will be OK, but then only after one day I will get it too. 

What I don't understand is the fact we already check for error in the response: https://github.com/iMicknl/python-tahoma-api/blob/master/pyhoma/client.py#L200

It's probably related to the fact we are in async mode.

**Comment by iMicknl** [comment]
@tetienne the part you shared contains `await response.json()` which could be the culprit looking at the error. I am not sure if the TaHoma API always returns a JSON response... (or aiohttp if there is no connection)

https://github.com/iMicknl/python-tahoma-api/blob/806ef525962ffcadb80ce2f4cbfe55950e965521/pyhoma/client.py#L209

**Comment by tetienne** [comment]
@iMicknl Ah yes you are right! We should check the type first. Then in HA, once an exception caught, we shloud recreate the session.

**Comment by iMicknl** [comment]
```
Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: [Errno 104] Connection reset by peer
Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: Cannot connect to host tahomalink.com:443 ssl:None [Try again]
Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: Cannot connect to host tahomalink.com:443 ssl:None [Connect call failed ('178.32.15.131', 443)]
Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: None
```

We need to work on the reconnection logic I believe, looks like the event listener has to be re registered sometimes.
